# Generated by Django 4.0.6 on 2023-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
